export const SECTION_ID = {
  ECOSYSTEM: {
    FIRST_SCREEN: "ECOSYSTEM_FIRST_SCREEN",
    OVERVIEW: "ECOSYSTEM_OVERVIEW",
    DAPPS: "ECOSYSTEM_DAPPS",
    VENTURES: "ECOSYSTEM_VENTURES",
    START: "ECOSYSTEM_START",
  },
};
